---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-storage
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/master/kubernetes/task2.1

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-storage
spec:
  volumeName: pv-storage
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-exchange-pvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exchange-pvc
  template:
    metadata:
      labels:
        app: exchange-pvc
    spec:
      containers:
      - name: busybox
        image: busybox:latest
        command:
            - sh
            - -c
            - |
              while true; do
                date >> /shared/output.txt
                chmod 644 /shared/output.txt
                sleep 5
              done 
        volumeMounts:
        - name: pv-storage
          mountPath: /shared
      - name: multitool
        image: praqma/network-multitool:latest
        command: ["/bin/sh", "-c"]
        args: ["tail -f /shared/output.txt"] 
        volumeMounts:
        - name: pv-storage
          mountPath: /shared
      volumes:
      - name: pv-storage
        persistentVolumeClaim:
          claimName: pvc-storage